server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://106.54.142.196:3306/shiro?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: Ws12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:data.sql
    initialization-mode: embedded

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      #naming:
       # strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    #content-type: text/html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

